language: bash
services: docker

env:
  - VERSION=7.1 MINOR=6
  - VERSION=7.0 MINOR=19
  - VERSION=5.6 MINOR=30
  - VERSION=5.3 MINOR=29

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION/fpm/alpine"
  - image="wodby/base-php:${VERSION}.${MINOR}"

script:
  - travis_retry docker build -t "$image" "${VARIANT:-.}"
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

after_success: |
  if [ "$TRAVIS_PULL_REQUEST" == "false" ] && ([ "$TRAVIS_BRANCH" == "master" ] || [ -n "$TRAVIS_TAG" ]); then
    docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    docker push "$image"
  fi

# vim:set et ts=2 sw=2:
