language: bash
services: docker

env:
  - VERSION=7.1 VARIANT=fpm/alpine
  - VERSION=7.0 VARIANT=fpm/alpine
  - VERSION=5.6 VARIANT=fpm/alpine
  - VERSION=5.3 VARIANT=fpm/alpine

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION"
  - image="wodby/base-php:${VERSION}${VARIANT:+-$VARIANT}"
  - image="${image//'/'/-}"

script:
  - travis_retry docker build -t "$image" "${VARIANT:-.}"
  - ~/official-images/test/run.sh "$image"

after_script:
  - docker images

# vim:set et ts=2 sw=2:
